### ISSUE TITLE
UI issue: "How to connect"

### ISSUE THREAD

**Issue by neuhaus** [mrdjohnson/llm-x#30]
I think this section is poorly placed, there should be a link to a page with these explanations in the "Model" section of the settings.

**Comment by mrdjohnson** [comment]
I can add a "?" Connections in the model section as well (especially when the connections fails) but I think having the "how to section" is useful to have on its own. 

It's also getting a UI refresh as well! Coming in the next day or so

**Comment by mrdjohnson** [comment]
- Left the how to connect section in place, instead of a user trying to click around to find it, i'll also adda quick link to pre-made connection types from the help section at a later time for faster transitionings

- help section follows drawer type structure of other setting panels now
- each connection type has a help section
- on "disconnected connection" page, add a direct link to `/help_section/connection_type` for the user
